name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Lab 3
      id: test-lab-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Lab 3
        setup-command: rm *.class; javac *.java
        command: java TileGraph
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-LAB-3_RESULTS: "${{steps.test-lab-3.outputs.result}}"
      with:
        runners: test-lab-3
